server:
  port: 11021

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: je1907
    password: 1234
    url: jdbc:mysql://localhost:3306/je1907_oders?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: qz03-provider-user
eureka:
  instance:
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://localhost:11100/eureka